language: python
python:
  - "3.5"
  - "3.6"
  
install:
  - pip install pipenv
  - pipenv install
  
script:
  - unittest discover
  
env:
  global:
    - WORKON_HOME=.pipenv/venvs
    - PIP_CACHE_DIR=.pipenv/pipcache

cache:
  directories:
    - .pipenv
